/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controle.Controle;
import javax.swing.JOptionPane;

/**
 *
 * @author ThomasJefferson
 */
public class Cadastro extends javax.swing.JFrame {
    MenuPrincipal TelaAnterior;
    /**
     * Creates new form Cadastro
     */
    private Cadastro() {
        initComponents();
    }
    
    public Cadastro(MenuPrincipal TelaAnterior) {
        this();
        this.TelaAnterior = TelaAnterior;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        Limpar = new javax.swing.JButton();
        Nome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        CPF = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        LValor = new javax.swing.JLabel();
        CampoMatricula = new javax.swing.JTextField();
        LMatricula = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aluno", "Empregado" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 124, -1));

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        Limpar.setText("Limpar");
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });
        getContentPane().add(Limpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));
        getContentPane().add(Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 190, -1));

        jLabel1.setText("Nome");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 140, -1));

        CPF.setText("CPF");
        getContentPane().add(CPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        getContentPane().add(jFormattedTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 90, -1));

        LValor.setText("Mensalidade");
        getContentPane().add(LValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));
        getContentPane().add(CampoMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 150, -1));

        LMatricula.setText("Matrícula");
        getContentPane().add(LMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        TelaAnterior.setVisible(false);
  
    }//GEN-LAST:event_formWindowOpened

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if(jComboBox1.getSelectedIndex() == 0){
            LMatricula.setVisible(true);
            CampoMatricula.setVisible(true);
            LValor.setText("Mensalidade");
        } else {
            LMatricula.setVisible(false);
            CampoMatricula.setVisible(false);
            LValor.setText("Salário");
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(jComboBox1.getSelectedIndex() == 0){
            if(CampoMatricula.getText().isEmpty() || Nome.getText().isEmpty() || jFormattedTextField1.getText().isEmpty() || jFormattedTextField2.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Campos Obrigatórios não preenchidos!");
            } else {
                double valor = Double.parseDouble(jFormattedTextField2.getText().replace(",", "."));
                if(Controle.CadastraAluno(Integer.parseInt(CampoMatricula.getText()), Nome.getText(), jFormattedTextField1.getText(), valor)){
                    CampoMatricula.setText("");
                    Nome.setText("");
                    jFormattedTextField1.setText("");
                    jFormattedTextField2.setText("");
                    JOptionPane.showMessageDialog(null, "Cadastro Efetuado!");
                }
                    
            }
        } else {
            if(Nome.getText().isEmpty() || jFormattedTextField1.getText().isEmpty() || jFormattedTextField2.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Campos Obrigatórios não preenchidos!");
            } else {
                double valor = Double.parseDouble(jFormattedTextField2.getText().replace(",", "."));
                if(Controle.CadastraEmpregado(Nome.getText(), jFormattedTextField1.getText(), valor)){
                    Nome.setText("");
                    jFormattedTextField1.setText("");
                    jFormattedTextField2.setText("");
                    JOptionPane.showMessageDialog(null, "Cadastro Efetuado!");
                }
                    
            }            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed
        CampoMatricula.setText("");
        Nome.setText("");
        jFormattedTextField1.setValue("");
        jFormattedTextField2.setValue("");
    }//GEN-LAST:event_LimparActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        TelaAnterior.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CPF;
    private javax.swing.JTextField CampoMatricula;
    private javax.swing.JLabel LMatricula;
    private javax.swing.JLabel LValor;
    private javax.swing.JButton Limpar;
    private javax.swing.JTextField Nome;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
