/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controle.Controle;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import logica.Aluno;
import logica.Empregado;

/**
 *
 * @author ThomasJefferson
 */
public class Relatorios extends javax.swing.JFrame {
    MenuPrincipal TelaAnterior;
    /**
     * Creates new form Relatorios
     */
    private Relatorios() {
        initComponents();
    }
    
    public Relatorios(MenuPrincipal TelaAnterior){
        this();
        this.TelaAnterior = TelaAnterior;
    }
    
    public void OrganizaPagar(){
        ArrayList<Empregado> empregados = new ArrayList<>();
        
        empregados = Controle.RetornaEmpregado();
        
        DefaultTableModel modelo = new DefaultTableModel();
        
        modelo.addColumn("ID");
        modelo.addColumn("Item");
        modelo.addColumn("Despesas");

        if(empregados.isEmpty()){
            modelo.addRow(new String[]{" ", " ", " "});
        } else {
            for(int i = 0; i < empregados.size(); i++){
                modelo.addRow(new String[]{String.valueOf(i), "Salário de: " + empregados.get(i).getNome(), String.valueOf(empregados.get(i).getSalario())});
            }
        }

        jTable1.setModel(modelo);                    
    }    

    public void OrganizaReceber(){
        ArrayList<Aluno> alunos = new ArrayList<>();
        
        alunos = Controle.RetornaAluno();
        
        DefaultTableModel modelo = new DefaultTableModel();
        
        modelo.addColumn("ID");
        modelo.addColumn("Item");
        modelo.addColumn("Receitas");

        if(alunos.isEmpty()){
            modelo.addRow(new String[]{" ", " ", " "});
        } else {
            for(int i = 0; i < alunos.size(); i++){
                modelo.addRow(new String[]{String.valueOf(i), "Mensalidade de: " + alunos.get(i).getNome(), String.valueOf(alunos.get(i).getMensalidade())});
            }
        }

        jTable1.setModel(modelo);                    
    }  
    
    public void OrganizaSaldo(){
        ArrayList<Aluno> alunos = new ArrayList<>();
        ArrayList<Empregado> empregados = new ArrayList<>();
        
        double total = 0.0;
        alunos = Controle.RetornaAluno();
        empregados = Controle.RetornaEmpregado();
        
        DefaultTableModel modelo = new DefaultTableModel();

        modelo.addColumn("Item");
        modelo.addColumn("Receitas");
        modelo.addColumn("Despesas");
        modelo.addColumn("Saldo");

        if(alunos.isEmpty()){
            modelo.addRow(new String[]{" ", " ", " ", " "});
        } else {
            for(int i = 0; i < alunos.size(); i++){
                total += alunos.get(i).getMensalidade();
                modelo.addRow(new String[]{"Mensalidade de: " + alunos.get(i).getNome(), String.valueOf(alunos.get(i).getMensalidade()), " " , String.valueOf(total)});
            }
        }


        if(empregados.isEmpty()){
            modelo.addRow(new String[]{" ", " ", " ", " "});
        } else {
            for(int i = 0; i < empregados.size(); i++){
                total -= empregados.get(i).getSalario();
                modelo.addRow(new String[]{"Salário de: " + empregados.get(i).getNome(), " ", String.valueOf(empregados.get(i).getSalario()), String.valueOf(total)});
            }
        }

        jTable1.setModel(modelo);            
            
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Contas a Pagar", "Contas a Receber", "Saldo" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if(jComboBox1.getSelectedIndex() == 0){
            OrganizaPagar();
        } else if (jComboBox1.getSelectedIndex() == 1){
            OrganizaReceber();
        } else {
            OrganizaSaldo();
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        TelaAnterior.setVisible(false);
        OrganizaPagar();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        TelaAnterior.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relatorios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
