/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controle.Controle;
import java.awt.Color;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author ThomasJefferson
 */
public class Cadastro extends javax.swing.JFrame {
    private MenuPrincipal telaAnterior;
    /**
     * Creates new form Cadastro
     */
    private Cadastro() {
        initComponents();
    }

    public Cadastro(MenuPrincipal telaAnterior) {
        this();
        this.telaAnterior = telaAnterior;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JLID = new javax.swing.JLabel();
        JTFID = new javax.swing.JTextField();
        EscolhaTipo = new javax.swing.JComboBox();
        JLValor = new javax.swing.JLabel();
        JTFNome = new javax.swing.JTextField();
        JLNome = new javax.swing.JLabel();
        JLCPF = new javax.swing.JLabel();
        JFTFValor = new javax.swing.JFormattedTextField();
        JLExtra = new javax.swing.JLabel();
        JFTFExtra = new javax.swing.JFormattedTextField();
        JBLimpar = new javax.swing.JButton();
        JFTFCPF = new javax.swing.JFormattedTextField();
        JBCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro");
        setResizable(false);
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentResized(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLID.setText("Matrícula:");
        jPanel1.add(JLID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));
        jPanel1.add(JTFID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 164, -1));

        EscolhaTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aluno", "Empregado", "Gerente", "Comissionado", "Fornecedor" }));
        EscolhaTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscolhaTipoActionPerformed(evt);
            }
        });
        jPanel1.add(EscolhaTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 165, -1));

        JLValor.setText("Mensalidade:");
        jPanel1.add(JLValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        jPanel1.add(JTFNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 260, -1));

        JLNome.setText("Nome:");
        jPanel1.add(JLNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        JLCPF.setText("CPF:");
        jPanel1.add(JLCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        try {
            JFTFValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(JFTFValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 94, -1));

        JLExtra.setText("Gratificação:");
        jPanel1.add(JLExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        JFTFExtra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jPanel1.add(JFTFExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 94, -1));

        JBLimpar.setText("Limpar");
        JBLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBLimparActionPerformed(evt);
            }
        });
        jPanel1.add(JBLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        try {
            JFTFCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JFTFCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JFTFCPFKeyReleased(evt);
            }
        });
        jPanel1.add(JFTFCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 160, -1));

        JBCadastrar.setText("Cadastrar");
        JBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(JBCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        EscolhaTipo.setSelectedIndex(0);
        JLExtra.setVisible(false);
        JFTFExtra.setVisible(false);
        telaAnterior.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        telaAnterior.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void EscolhaTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscolhaTipoActionPerformed
        if(EscolhaTipo.getSelectedIndex() == 0){
            JLID.setVisible(true);
            JTFID.setVisible(true);
            JLID.setText("Matrícula");
            JLCPF.setText("CPF");
            JLExtra.setVisible(false);
            JFTFExtra.setVisible(false);
            JLNome.setText("Nome");
            JLValor.setText("Mensalidade");
            JTFID.setText("");            
            JTFNome.setText("");                  
            JFTFValor.setText("");        
            JFTFExtra.setText("");   
            JFTFCPF.setValue("");
            JFTFCPF.setBackground(Color.white);
            try{
                MaskFormatter formatocpf = new MaskFormatter("###.###.###-##");
                JFTFCPF.setFormatterFactory(new DefaultFormatterFactory(formatocpf));
            }catch (ParseException ex){
                JOptionPane.showMessageDialog(null, "Formato de CPF Inválido!", "Máscara Inválida!", JOptionPane.ERROR_MESSAGE, null);
            }
            try{
                MaskFormatter formatoValor = new MaskFormatter("###,##");
                JFTFValor.setFormatterFactory(new DefaultFormatterFactory(formatoValor));
            }catch (ParseException ex){
                JOptionPane.showMessageDialog(null, "Formato de VALOR Inválido!", "Máscara Inválida!", JOptionPane.ERROR_MESSAGE, null);
            }
            if(JFTFExtra.isVisible()){
                JFTFExtra.setText("");
            }
        } else if (EscolhaTipo.getSelectedIndex() == 1){
            JLID.setVisible(false);
            JLCPF.setText("CPF");
            JLExtra.setVisible(false);
            JFTFExtra.setVisible(false);
            JLNome.setText("Nome");
            JLValor.setText("Salário");    
            JTFID.setVisible(false);            
            JTFNome.setText("");              
            JFTFValor.setText("");            
            JFTFExtra.setText(""); 
            JFTFCPF.setValue("");
            JFTFCPF.setBackground(Color.white);
            try {
                MaskFormatter formatocpf = new MaskFormatter("###.###.###-##");
                JFTFCPF.setFormatterFactory(new DefaultFormatterFactory(formatocpf));
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null, "Formato de CPF Inválido!", "Máscara Inválida!", JOptionPane.ERROR_MESSAGE, null);
            }
            if(JFTFExtra.isVisible()){
                JFTFExtra.setText("");
            }            
        } else if (EscolhaTipo.getSelectedIndex() == 2){
            JLID.setVisible(false);
            JLCPF.setText("CPF");
            JLExtra.setVisible(true);
            JLExtra.setText("Gratificação");
            JFTFExtra.setVisible(true);
            JLNome.setText("Nome");
            JLValor.setText("Salário");                  
            JTFID.setVisible(false);             
            JTFNome.setText("");                
            JFTFValor.setText("");            
            JFTFExtra.setText(""); 
            JFTFCPF.setValue("");
            JFTFCPF.setBackground(Color.white);
            try {
                MaskFormatter formatocpf = new MaskFormatter("###.###.###-##");
                JFTFCPF.setFormatterFactory(new DefaultFormatterFactory(formatocpf));
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null, "Formato de CPF Inválido!", "Máscara Inválida!", JOptionPane.ERROR_MESSAGE, null);
            }
            if(JFTFExtra.isVisible()){
                JFTFExtra.setText("");
            }
        } else if (EscolhaTipo.getSelectedIndex() == 3){
            JLID.setVisible(false);
            JLCPF.setText("CPF");
            JLExtra.setVisible(true);
            JLExtra.setText("Percentual");
            JFTFExtra.setVisible(true);
            JLNome.setText("Nome");
            JLValor.setText("Salário");               
            JTFID.setVisible(false);            
            JTFNome.setText("");             
            JFTFValor.setText("");            
            JFTFExtra.setText(""); 
            JFTFCPF.setValue("");
            JFTFCPF.setBackground(Color.white);
            try {
                MaskFormatter formatocpf = new MaskFormatter("###.###.###-##");
                JFTFCPF.setFormatterFactory(new DefaultFormatterFactory(formatocpf));
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null, "Formato de CPF Inválido!", "Máscara Inválida!", JOptionPane.ERROR_MESSAGE, null);
            }
            if(JFTFExtra.isVisible()){
                JFTFExtra.setText("");
            }            
        } else {
            JLID.setVisible(false);
            JLCPF.setText("CNPJ");
            JLExtra.setVisible(false);
            JLExtra.setText("Gratificação");
            JFTFExtra.setVisible(false);
            JLNome.setText("Nome");
            JLValor.setText("Valor Contrato");               
            JTFID.setVisible(false);            
            JTFNome.setText("");              
            JFTFValor.setText("");            
            JFTFCPF.setValue("");
            JFTFCPF.setBackground(Color.white);
            try {
                MaskFormatter formato = new MaskFormatter("##.###.###/####-##");
                JFTFCPF.setFormatterFactory(new DefaultFormatterFactory(formato));
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null, "Formato de CNPJ Inválido!", "Máscara Inválida!", JOptionPane.ERROR_MESSAGE, null);
            }
            if(JFTFExtra.isVisible()){
                JFTFExtra.setText("");
            }
        }
    }//GEN-LAST:event_EscolhaTipoActionPerformed

    private void JBLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBLimparActionPerformed
        JTFID.setText("");
        JTFNome.setText("");
        JFTFValor.setText("");   
        JFTFCPF.setValue("");
        JFTFCPF.setBackground(Color.white);
        if(JFTFExtra.isVisible()){
            JFTFExtra.setText("");
        }
    }//GEN-LAST:event_JBLimparActionPerformed

    private void JBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCadastrarActionPerformed
        if(JTFNome.getText().isEmpty() || JFTFCPF.getText().isEmpty() || JFTFValor.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campos Obrigatórios não Preenchidos!", "Cadastro Inválido!", JOptionPane.WARNING_MESSAGE, null);
        } else {
                String teste = JFTFValor.getText().replace(",", ".");
                double valor = Double.parseDouble(teste);
                if(EscolhaTipo.getSelectedIndex() == 0){ //Cadastro Aluno
                    if(!JTFID.getText().isEmpty()){
                        if(Controle.cadastroAluno(Integer.parseInt(JTFID.getText()), JTFNome.getText(), JFTFCPF.getText(), valor)){
                            JBLimparActionPerformed(evt);
                            JOptionPane.showMessageDialog(null, "Aluno Cadastrado com Sucesso!");
                        }                   
                    } else {
                        JOptionPane.showMessageDialog(null, "Campos Obrigatórios não preenchidos!");
                    }
                } else if (EscolhaTipo.getSelectedIndex() == 1){ //Cadastro Empregado
                        if(Controle.cadastroEmpregado(JTFNome.getText(), JFTFCPF.getText(), valor)){
                            JBLimparActionPerformed(evt);
                            JOptionPane.showMessageDialog(null, "Empregado Cadastrado com Sucesso!");
                        }
                    } else if (EscolhaTipo.getSelectedIndex() == 2){ //Cadastro Gerente
                        double vgrat=0.0;
                        try{
                            String grat = JFTFExtra.getText().replace(",", ".");
                            vgrat = Double.parseDouble(grat);
                        } catch (NumberFormatException ex){
                            vgrat = 0.0;
                        } finally{
                            if(Controle.cadastroGerente(JTFNome.getText(), JFTFCPF.getText(), valor, vgrat)){
                                JBLimparActionPerformed(evt);
                                JOptionPane.showMessageDialog(null, "Gerente Cadastrado com Sucesso!");
                            }
                        }
                    } else if (EscolhaTipo.getSelectedIndex() == 3){ //Cadastro Comissionado
                        double vperc = 0.0;
                        try{
                            String perc = JFTFExtra.getText().replace(",", ".");
                            vperc = Double.parseDouble(perc);
                        } catch (NumberFormatException ex){
                            vperc = 0.0;
                        } finally {
                            if(Controle.cadastroComissionado(JTFNome.getText(), JFTFCPF.getText(), valor, vperc)){
                                JBLimparActionPerformed(evt);
                                JOptionPane.showMessageDialog(null, "Comissionado Cadastrado com Sucesso!");
                            }
                        }
                } else if (EscolhaTipo.getSelectedIndex() == 4){  //Cadastro Fornecedor
                        if(Controle.cadastroFornecedor(JTFNome.getText(), JFTFCPF.getText(), valor)){
                            JBLimparActionPerformed(evt);
                            JOptionPane.showMessageDialog(null, "Fornecedor Cadastrado com Sucesso!");
                        }
                    }
        } 
    }//GEN-LAST:event_JBCadastrarActionPerformed

    private void JFTFCPFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JFTFCPFKeyReleased
        String testejftf = JFTFCPF.getText();
        testejftf = testejftf.replace(".", "");
        testejftf = testejftf.replace("-", "");
        testejftf = testejftf.replace("/", "");
        testejftf = testejftf.replace(" ", "");
        if(EscolhaTipo.getSelectedIndex() == 4){
            if(testejftf.length() == 14){
                if(Controle.verificaCNPJ(JFTFCPF.getText())){
                    JFTFCPF.setBackground(Color.green);
                } else {
                    JFTFCPF.setBackground(Color.red);
                }
            } else {
                JFTFCPF.setBackground(Color.white);
            }
        } else {
            if(testejftf.length()==11){
                if(Controle.verificaCPF(JFTFCPF.getText())){
                    JFTFCPF.setBackground(Color.green);
                } else {
                    JFTFCPF.setBackground(Color.red);
                }
            } else {
                JFTFCPF.setBackground(Color.white);
            }
        }
    }//GEN-LAST:event_JFTFCPFKeyReleased

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_formPropertyChange

    private void jPanel1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1ComponentResized

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox EscolhaTipo;
    private javax.swing.JButton JBCadastrar;
    private javax.swing.JButton JBLimpar;
    private javax.swing.JFormattedTextField JFTFCPF;
    private javax.swing.JFormattedTextField JFTFExtra;
    private javax.swing.JFormattedTextField JFTFValor;
    private javax.swing.JLabel JLCPF;
    private javax.swing.JLabel JLExtra;
    private javax.swing.JLabel JLID;
    private javax.swing.JLabel JLNome;
    private javax.swing.JLabel JLValor;
    private javax.swing.JTextField JTFID;
    private javax.swing.JTextField JTFNome;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
